### ISSUE TITLE
Open JDK 11 Dependency | ClassNotFoundException: javax.xml.bind.JAXBContext`

### ISSUE THREAD

**Issue by jithinsarath** [damadei/BotServiceStressToolkit#3]
For anyone using openjdk 11 and above, you will get an exception when running the JMeter tests. like below `Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext`

Jax is deprecated and can't be loaded using addmodule command at runtime anymore. To resolve this, you need to define dependency in your maven's pom.xml like below

`		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.2.11</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.2.11</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>2.2.11</version>
		</dependency>
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>`

**Comment by damadei** [comment]
Fixed in the new version. thanks for the heads up.
