### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by jithinsarath** [damadei/BotServiceStressToolkit#4]
Most of the bots in the real world today use HTTPS. Your notes say that this is not supported. What needs to be done to enable the toolkit to handle HTTPS. 

I can help.

**Comment by damadei** [comment]
Hi @jithinsarath,

What is not supported today is just HTTPS to the callback server that is spun up by JMETER. HTTPS used by the bot is supported without issues.

Daniel
