### ISSUE TITLE
Support for "unsolicited" messages

### ISSUE THREAD

**Issue by Xeviva** [damadei/BotServiceStressToolkit#5]
Hi, 
We have a use case whereby we send a message to every active conversation from the server in an unsolicited manner, i.e without sending a message to the bot first. Sort of like a push notification. We would like to be able to verify that these are received, and hopefully how quickly.

We are looking to load test this scenario and can trigger these messages via an api call to our application from outside the bot, but we're having difficulty in verifying they are received. I don't think this is possible with the current Bot Service: Message Sampler.

I think it would require a new sampler type that waits for a response without sending a message, possibly with it's own time out setting to be able to test this fully. Is there a way to achieve this with the BotServiceStressToolkit as is?

**Comment by damadei** [comment]
Hi @Xeviva,

I believe this is not supported as the Bot Builder Stress Testing Tool will always try to correlate the message. If no correlation, the message will be discarded.

Not sure if this is something we can handle with this toolkit.

Daniel

**Comment by Xeviva** [comment]
Do you think it would be possible to extend the Bot Stress Testing tool to add this functionality? I could help with this if you think it possible.

**Comment by damadei** [comment]
Hi @Xeviva, 

Really not sure if this fits into the way JMeter works, nevertheless, it's open source, the code is available, feel free to try it :)

Daniel
